### ISSUE TITLE
Updating Octokat to 0.6.0-0 breaks GitHub Fetch All Repos

### ISSUE THREAD

**Issue by NuttyNeko** [ChristianMurphy/nicest#429]
Updating octokat from `0.5.0-beta.0` to `0.6.0-0"` in #425 breaks [here](https://github.com/ChristianMurphy/nicest/blob/4ff1de851f74ee2ba20af28c93aec68bd0deedf9/modules/code-project/handler/choose-repository.js#L28) and [here](https://github.com/ChristianMurphy/nicest/blob/4ff1de851f74ee2ba20af28c93aec68bd0deedf9/modules/github/handler/list.js#L28).

```
snowshoe :: ~/Code/nicest » node bin/cli.js dev         
Server running at: http://localhost:8080/nicest
Debug: internal, implementation, error 
    TypeError: Uncaught error: Github.me.repos.fetchAll is not a function
    at list (/home/nutty/Code/nicest/modules/github/handler/list.js:28:10)
    at Object.internals.handler (/home/nutty/Code/nicest/node_modules/hapi/lib/handler.js:96:36)
    at request._protect.run (/home/nutty/Code/nicest/node_modules/hapi/lib/handler.js:30:23)
    at internals.Protect.run (/home/nutty/Code/nicest/node_modules/hapi/lib/protect.js:62:12)
    at exports.execute (/home/nutty/Code/nicest/node_modules/hapi/lib/handler.js:24:22)
    at each (/home/nutty/Code/nicest/node_modules/hapi/lib/request.js:380:16)
    at iterate (/home/nutty/Code/nicest/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/home/nutty/Code/nicest/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at authenticated (/home/nutty/Code/nicest/node_modules/hapi/lib/auth.js:417:20)
    at validate (/home/nutty/Code/nicest/node_modules/hapi/lib/auth.js:424:20)
    at after (/home/nutty/Code/nicest/node_modules/hapi/lib/auth.js:331:47)
    at Hoek.once (/home/nutty/Code/nicest/node_modules/hapi/lib/protect.js:52:16)
    at wrapped (/home/nutty/Code/nicest/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at request.server._replier.interface (/home/nutty/Code/nicest/node_modules/hapi/lib/auth.js:335:115)
    at Function.wrapped [as _next] (/home/nutty/Code/nicest/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at Function.internals.continue (/home/nutty/Code/nicest/node_modules/hapi/lib/reply.js:125:10)
```

Re-adding the fetch all shim from 9fadee347b6e349ebe9703dc6cc3443f4423d5d3 seems to fix this.
Is `fetchAll()` no longer a native method in `0.6.0-0`?

**Comment by ChristianMurphy** [comment]
Good question.
`fetchAll` is exposed by an octokat plugin.
But that plugin should be enabled by default...
https://github.com/philschatz/octokat.js/blob/255d19200810d0b8777a6682a2caa4c60e41d3ef/src/octokat.coffee#L15

**Comment by ChristianMurphy** [comment]
Rolling back to 0.5 for now, will investigate 0.6 more later
